name: "Hui Yi C."
description: "I'm Hui Yi, a huge fan of Philz and corgis. I love exploring interaction design and my favourite hangouts include Product Hunt and this website. 
In my free time, I dabble in building prototypes and interactions for fun with Axure and FramerJS. Currently with the Product team at Carousell.t"

url: "http://huiyichia.com"

paginate: 1

markdown: rdiscount
permalink: pretty